# https://github.com/codecov/support/blob/master/codecov.yml
codecov:
  bot: dlang-bot

coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    # Learn more at https://codecov.io/docs#yaml_default_commit_status
    project: true
    patch: true
    changes: false

comment: false
